### ISSUE TITLE
go-ethereum v1.8 dependency fails

### ISSUE THREAD

**Issue by p4u** [iden3/go-iden3#123]
## Problem

Go Ethereum v1.8.23 depends on prometheus/flock which does not exist. 

go-iden3 depend on go-ethereum v.1.8.23 (https://github.com/iden3/go-iden3/blob/master/go.mod#L10)

So any project depending on go-iden3 depends on go-ethereum and crashes when trying to fetch prometheus/flock

## Solution

This bug in go-ethereum was addressed and fixed on 4th April
https://github.com/ethereum/go-ethereum/pull/19376/commits/c676bc94859d387318e39daa7c6962ea862cf6ce

Until Go Ethereum v1.9 is not released (should be soon), use Master instead. Just update go-iden3 go.mod file

```
go get github.com/ethereum/go-ethereum@master
git add go.mod
...
```

Or just add and commit this line in the go.mod file.
`github.com/ethereum/go-ethereum v1.8.22-0.20190513125017-07d2d83c315a`

Please, create a new TAG once this is fixed so go module will work out-of-the-box for those using your repo.

Thanks!

**Comment by arnaucube** [comment]
Thanks!
Done :)
ttps://github.com/iden3/go-iden3/tree/v0.0.4
